"""empty message

Revision ID: 526c6323b013
Revises: 0bc098b5841e
Create Date: 2023-06-06 16:15:34.153796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526c6323b013'
down_revision = '0bc098b5841e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('peoples', schema=None) as batch_op:
        batch_op.drop_constraint('peoples_url_key', type_='unique')
        batch_op.drop_column('url')
        batch_op.drop_column('created')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('created')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.VARCHAR(length=30), autoincrement=False, nullable=True))

    with op.batch_alter_table('peoples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('peoples_url_key', ['url'])

    # ### end Alembic commands ###
