"""empty message

Revision ID: 71243800aeed
Revises: f19d3a6b122e
Create Date: 2023-06-05 13:43:17.601645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71243800aeed'
down_revision = 'f19d3a6b122e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_homeworld_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['homeworld'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('people_homeworld_fkey', 'people', ['homeworld'], ['id'])

    # ### end Alembic commands ###
